### PR TITLE
Added more functionality  

### PR DESCRIPTION
**Pull request by AizazAZ**
Android library that provides an easy to use service to upload files with Android Notification Center integration. Added functionality to report status of files and upload request whether they have uploaded successfully or failed. You can push as much UploadRequest as you need, also each UplaodRequest can have multiple files but it will run one request (one file from request) at a time (you can queue as many requests are you want), it will update progress bar notification for each file after every 4 seconds. Please note that Examples project is outdated, see example in the description

### CODE REVIEW

**Comment by alexbbb** [comment]
Hi @AizazAZ 
Sorry for the delay of my response, but I haven't had enough time to properly check the code you submitted until today. Right now, it's hard to merge your pull request as-is, but I've seen some interesting additions you've made, like the overall progress of the operation, the delayed notification progress update to prevent lag and some additions to the broadcast receiver to better monitor single file upload progress. Right now I'm considering to migrate the entire project in Android Studio and to publish it to jCentral. There are already some features that I plan to add and toghether with them I'll also add some of your additions. You will be added to the contributors (annotation @author in the source files). I'll let you know which code I've copied from your solution once I'm done. Thank you again for the time you invested on this library!

**Comment by AizazAZ** [comment]
Welcome and really thanks for such kind reply. I'll hopefully add some more features after your update. best of luck and thanks you very much for this library, it saved me lot of time :+1:

**Comment by alexbbb** [comment]
@AizazAZ I've recently read some RFCs regarding standard http multipart form upload. I've seen that you have implemented a mechanism which tells the programmer which files have failed in the multipart request. Based on the server implementations that I have (php and node.js), if the multipart request fails at some point, all the successfully uploaded files which are part of the failed http multipart request gets automatically deleted by the server, so what's the point in notifying the programmer which files have failed, since he has to do the whole multipart request again? What do you think about it? Am I missing something?

**Comment by AizazAZ** [comment]
If sever is accepting multiple files in one HTTP POST reqeust then there is no need to tell about individual file but in my case I am sending one file at a time, because for some reason server implementation (I have no control over it) can accept only one file in one request at a time. so as some file fails I report it and on the interface user can again tap on retry to submit it again. Sorry that was a confusion at my part.

**Comment by AizazAZ** [comment]
I am also thinking about supporting GZip compression and rather than using HTTP Client we should give user freedom to use any HTTP Client library he is happy to use, some libraries support GZip compression support out of the box. Here is Android's default implementation http://developer.android.com/reference/java/util/zip/GZIPOutputStream.html

**Comment by AizazAZ** [comment]
Please let me know if you have updated :)

**Comment by alexbbb** [comment]
@AizazAZ 
Added DotShare in the list of apps which uses the library and just published a new release :)

Have you done anything about the GZIP Compression? Currently the upload service uses android standard HttpUrlConnection, which is the recommended from Google.

Regarding this pull request, I'm considering to implement the following ideas in the next milestone:
- single file upload progress
- delayed notification update

The code has changed from the one you used to make the modifications, so the two ideas needs to be re-implemented. If you want to contribute, we can get in touch and plan how to implement them together, so let me know :)

**Comment by AizazAZ** [comment]
Yeah sure, I'll re pull the latest changes :+1:

**Pull request closed without merging**
